//Home.js
export const SWITCH_TO_TIMER = 'SWITCH_TO_TIMER';
export const SWITCH_TO_EDIT = 'SWITCH_TO_EDIT';

//Edit.js
export const ADD_NEW_CALENDAR_ENTRY = 'ADD_NEW_CALENDAR_ENTRY';
export const HANDLE_DETAILS_CHANGE = 'HANDLE_DETAILS_CHANGE';
export const HANDLE_TITLE_CHANGE = 'HANDLE_TITLE_CHANGE';
export const HANDLE_DATE_CHANGE = 'HANDLE_DATE_CHANGE';




